#THE CREDENTIALS HERE ARE FOR LOCAL DEVELOPMENT ONLY, DO NOT USE THEM IN PRODUCTION
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=APP_USER
spring.datasource.password=AppPass123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.default_schema=ORG_BDO
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

#Spring Security
spring.security.user.name=payment-user
spring.security.user.password=payment-password
spring.security.user.roles=USER
